---
- hosts: 192.168.12.81, 192.168.12.82, 192.168.12.83, 192.168.12.84, 192.168.12.85, 192.168.12.86, 192.168.12.88, 192.168.12.89, 192.168.12.90, 192.168.12.91, 192.168.12.92, 192.168.12.94, 192.168.12.97, 192.168.12.98, 192.168.12.99 #, 192.168.12.100 #192.168.12.87, 192.168.12.93, 192.168.12.95, 192.168.12.96, 192.168.12.100
  remote_user: videk
  tasks:

# If it is still running, stop the container
# (TODO pointless? collect_results is called only when all containers are stopped)
  - name: Stop docker container (target)
    ignore_errors: yes
    command: docker stop target

# Get measurements from container to device
  - name: Copy file from the container
    command: docker cp target:/root/logatec-experiment/results/ .
    args:
      chdir: ~/deploy/logatec-experiment

# Fetch measurements from device to SMS container --> from there they will be forwarded to Github
# On SMS container there is: videk-ci/<tag_name>/ folder...in it, there are logatec-experiment (a clone from
# Github repo) and a folder out. We are calling this script from logatec-experiment/deployment/ansible, so dest:
# is then ../../../out
  - name: Fetch data file to out folder
    synchronize:
      src: "{{ item }}"
      dest: ../../../out/
      mode: pull
    with_items: 
      - "~/deploy/logatec-experiment/results/*.txt"
      - "~/deploy/logatec-experiment/results/*.log"

# TODO: Leave results on devices?
#  - name: Delete results
#    file: 
#      path:  ~/deploy/logatec-experiment/results
#      state: absent


# TODO: 
# Should we stop controller container or will it stop automatically?
# It can stop automatically...but how to access log files then? Another Ansible playbook?
# With another bash script or should I put it in the same one?
# $ docker stop controller  --> docker stop will stop the broker gracefully...docker kill will not
# $ docker cp controller:/root/logatec-experiment/controller_broker.log .
# $ sync to out
