---
- hosts: 192.168.12.51, 192.168.12.52, 192.168.12.53, 192.168.12.54, 192.168.12.55, 192.168.12.56, 192.168.12.66, 192.168.12.67, 192.168.12.69, 192.168.12.70
  remote_user: videk
  tasks:

  #- name: Stop docker container (controller_BLE)
  #  command: docker stop controller_BLE
  
# If it is still running, stop the container
# (TODO pointless? collect_results is called only when all containers are stopped)
  - name: Stop docker container (target)
    ignore_errors: yes
    command: docker stop target_BLE

# Get measurements from container to device
  - name: Copy file from the container
    #command: docker cp controller_BLE:/root/logatec-experiment/deployment/tasks/results/ .
    command: docker cp target_BLE:/root/logatec-experiment/results/ .
    args:
      chdir: ~/deploy/logatec-experiment

# Fetch measurements from device to SMS container --> from there they will be forwarded to Github
# On that container we have: videk-ci/<tag_name>/ folder...in it, there are logatec-experiment (a clone from
# Github repo) and a folder out. We are calling this script from logatec-experiment/deployment/ansible, so dest:
# is then ../../../out
  - name: Fetch data file to out folder
    synchronize:
      src: "{{ item }}"
      dest: ../../../out/
      mode: pull
    with_items: 
      - "~/deploy/logatec-experiment/results/*.txt"
      - "~/deploy/logatec-experiment/results/*.log"

# Delete results from device
  - name: Delete results
    file: 
      path:  ~/deploy/logatec-experiment/results
      state: absent

# TODO: Leave results on devices?
#  - name: Delete results
#    file: 
#      path:  ~/deploy/logatec-experiment/results
#      state: absent
