---
- hosts: 192.168.12.81, 192.168.12.83
  remote_user: videk
  tasks:

  #- name: Stop docker container (controller_BLE)
  #  command: docker stop controller_BLE
  
# If it is still running, stop the container
  - name: Stop docker container (target)
    ignore_errors: yes
    command: docker stop target

# Get measurements from container
  - name: Copy file from the container
    #command: docker cp controller_BLE:/root/logatec-experiment/deployment/tasks/results/ .
    command: docker cp target:/root/logatec-experiment/results/ .
    args:
      chdir: ~/deploy/logatec-experiment

# Fetch measurements to videk container --> from there they will be forwarded to Github
# On that container we have: videk-ci/<tag_name>/ folder...in it, there are logatec-experiment (a clone from
# Github repo) and a folder out. We are calling this script from logatec-experiment/deployment/ansible, so dest:
# is then ../../../out
  - name: Fetch data file to out folder
    synchronize:
      src: "{{ item }}"
      dest: ../../../out/
      mode: pull
    with_items: "~/deploy/logatec-experiment/results/*.txt"

  - name: Delete results
    file: 
      path:  ~/deploy/logatec-experiment/results
      state: absent
