---
- hosts: 192.168.12.81
  remote_user: videk
  
  vars:
    technology: master

  tasks:
    - name: Stop the docker container
      ignore_errors: yes
      command: docker stop target-{{ technology }}

    - name: Copy file from the container
      command: docker cp target-{{ technology }}:/root/logatec-experiment/results/ .
      args:
        chdir: ~/deploy/logatec-experiment

  # Fetch measurements from device to SMS container --> from there they will be forwarded to Github
  # On SMS container there is: videk-ci/<tag_name>/ folder...in it, there are logatec-experiment (a clone from
  # Github repo) and a folder out. We are calling this script from logatec-experiment/deployment/ansible, so dest:
  # is then ../../../out
    - name: Fetch data file to out folder
      synchronize:
        src: "{{ item }}"
        dest: ../../../out/
        mode: pull
      with_items: 
        - "~/deploy/logatec-experiment/results/*.txt"
        - "~/deploy/logatec-experiment/results/*.log"
  
  # Delete results from a device
    - name: Delete results
      file: 
        path:  ~/deploy/logatec-experiment/results
        state: absent




# Controller cleanup 
- hosts: videk_server
  remote_user: videk

  tasks:
    - name: Stop controller
      ignore_errors: yes
      command: "{{ item }}"
      with_items:
        - docker kill controller-{{ technology }}
        - docker cp controller-{{ technology }}:/root/logatec-experiment/ECMS_controller.log .
        - docker rm controller-{{ technology }}
      args:
        chdir: ~/deploy/logatec-experiment
  
    - name: Move logging file 
      synchronize:
        src: ~/deploy/logatec-experiment/*.log
        dest: ../../../out/
        mode: pull
  
    - name: Delete results
      file: 
        path:  ~/deploy/logatec-experiment/*.log
        state: absent
  