---
- hosts: 192.168.12.51, 192.168.12.52, 192.168.12.53, 192.168.12.54, 192.168.12.55, 192.168.12.56, 192.168.12.57, 192.168.12.58, 192.168.12.59, 192.168.12.60, 192.168.12.61, 192.168.12.62, 192.168.12.63, 192.168.12.64, 192.168.12.65, 192.168.12.66, 192.168.12.67, 192.168.12.68, 192.168.12.69, 192.168.12.70,                   
  remote_user: videk
  tasks:

# If it is still running, stop the container
# (TODO pointless? collect_results is called only when all containers are stopped)
  - name: Stop docker container (target)
    ignore_errors: yes
    command: docker stop target_ble

# Get measurements from container to device
  - name: Copy file from the container
    command: docker cp target_ble:/root/logatec-experiment/results/ .
    args:
      chdir: ~/deploy/logatec-experiment

# Fetch measurements from device to SMS container --> from there they will be forwarded to Github
# On SMS container there is: videk-ci/<tag_name>/ folder...in it, there are logatec-experiment (a clone from
# Github repo) and a folder out. We are calling this script from logatec-experiment/deployment/ansible, so dest:
# is then ../../../out
  - name: Fetch data file to out folder
    synchronize:
      src: "{{ item }}"
      dest: ../../../out/
      mode: pull
    with_items: 
      - "~/deploy/logatec-experiment/results/*.txt"
      - "~/deploy/logatec-experiment/results/*.log"

# Delete results from device
  - name: Delete results
    file: 
      path:  ~/deploy/logatec-experiment/results
      state: absent


# TODO: 
# Should we stop controller container or will it stop automatically?
# It can stop automatically...but how to access log files then? Another Ansible playbook?
# With another bash script or should I put it in the same one?
# $ docker stop controller  --> docker stop will stop the broker gracefully...docker kill will not
# $ docker cp controller:/root/logatec-experiment/controller_broker.log .
# $ sync to out
