# TODO
# Option: run the script with strategy: free, so all the nodes will run simultaneously but they will not wait for each other 

---
- hosts: 192.168.12.51, 192.168.12.52, 192.168.12.53, 192.168.12.54, 192.168.12.55, 192.168.12.56, 192.168.12.66, 192.168.12.67, 192.168.12.69, 192.168.12.70
  strategy: free
  remote_user: videk

# Select which application to test, duration in minutes
  vars:
    application: 00_demo
    duration: 10

  tasks:
  - name: Create directory
    file:
      path: ~/deploy/logatec-experiment
      state: directory

# Recursive option will also download the sub-modules
# Update will pull the changes from Github
# Force will delete local changes
# Version you can change which branch to pull
  - name: Pull changes from github
    git:
      repo: git@github.com:logatec3/logatec-experiment.git
      dest: ~/deploy/logatec-experiment
      recursive: no
      update: yes
      force: yes
      depth: 1
      version: ble-monitor

# Build...with -f flag so we can later copy logatec-experiment directory into container
# with Dockerfile command COPY...else we get error "Forbidden path outside the build context"
  - name: Build docker file
    command: docker build -t lgtc-ble-experiment -f deployment/docker/Dockerfile .
    args:
      chdir: ~/deploy/logatec-experiment

  - name: Cleanup old docker containers (target_BLE)
    register: target
    ignore_errors: yes
    command: "{{ item }}"
    with_items:
      - docker kill target_BLE
      - docker rm target_BLE

    # Root node
  - name: Run docker image 
    command: docker run --name target_BLE --privileged --net=host -it -e TARGET=run_experiment -e APP_DIR="{{application}}" -e APP_DURATION_MIN="{{duration}}" lgtc-ble-experiment
