# TODO
# Option: run the script with strategy: free, so all the nodes will run simultaneously but they will not wait for each other 

---
- hosts: 192.168.12.156
  strategy: free
  remote_user: videk

# Select which application to test, duration in minutes and additional options (none/monitor/master/slave)
  vars:
    technology: UWB
    application: 00_demo
    duration: 10
    option: none
    master_node: "192.168.12.155"

  tasks:
  - name: Create directory
    file:
      path: ~/deploy
      state: directory

  - name: Deploy experiment repository
    synchronize:
      src: "{{ lookup('env','PWD') }}"
      dest: ~/deploy
      delete: yes
      recursive: yes

  - name: Build docker file
    command: docker build -t logatec-experiment-uwb -f deployment/docker/Dockerfile . 
    args:
      chdir: ~/deploy/logatec-experiment

  - name: Cleanup old docker containers (target-{{ technology }})
    register: target
    ignore_errors: yes
    command: "{{ item }}"
    with_items:
      - docker kill target-{{ technology }}
      - docker rm target-{{ technology }}

  - name: Run docker image
    command: docker run --name target-{{ technology }} --privileged --net=host -e APP="{{application}}" -e APP_DUR="{{duration}}" -e OPTION="slave" logatec-experiment-uwb
    when: inventory_hostname != master_node

  - name: Run anchor docker image
    command: docker run --name target-{{ technology }} --privileged --net=host -e APP="{{application}}" -e APP_DUR="{{duration}}" -e OPTION="master"  logatec-experiment-uwb
    when: inventory_hostname == master_node
