---
#############################################################################################################
# RELEASE TARGETS
#############################################################################################################
# Ansible playbook script that deploys experiment application to the testbed nodes.
#
# Before deploying an experiment, select:
#
#   *) Participating nodes    - by entering their IP address or a cluster name under the hosts variable. 
#                               Cluster names are defined in the /inventory/logatec_testbed file.
#   *) Experiment application - by entering application folder name under the application variable.
#   *) Experiment duration    - by entering minutes to the duration variable.
#   *) Additional options     - default is none. monitor applies ECMS service.                     
#
#############################################################################################################

- hosts: 192.168.12.81
  strategy: free
  remote_user: videk

  vars:
    technology: master
    application: 00_template
    duration: 20
    option: none

  tasks:
    - name: Create directory
      file:
        path: ~/deploy
        state: directory

    - name: Deploy experiment repository
      synchronize:
        src: "{{ lookup('env','PWD') }}"
        dest: ~/deploy
        delete: yes
        recursive: yes
  
    - name: Build the docker file
      command: docker build -t logatec-experiment -f deployment/docker/Dockerfile . 
      args:
        chdir: ~/deploy/logatec-experiment
  
    - name: Cleanup old docker containers
      ignore_errors: yes
      command: "{{ item }}"
      with_items:
        - docker kill target-{{ technology }}
        - docker rm target-{{ technology }}
  
    - name: Run docker container
      command: docker run --name target-{{technology}} --privileged --net=host -e APP="{{application}}" -e APP_DUR="{{duration}}" -e OPTION="{{option}}" logatec-experiment
  