# From SMS platform container connect back to Videk server. 
# Run experiment-controller container (in daemon mode, so Ansible continues to release_targets.yml)

---
- hosts: 172.17.0.1
  remote_user: videk

  vars:
    radio_type: BLE
    device_num: 9

  tasks: 
  - name: Create directory
    file:
      path: ~/deploy/logatec-experiment
      state: directory

  - name: Pull all changes from github
    git:
      repo: git@github.com:logatec3/logatec-experiment.git
      dest: ~/deploy/logatec-experiment
      recursive: no
      update: yes
      force: yes
      depth: 1
      version: experiment/BLE

  - name: Build docker file
    command: docker build -t controller-ble -f monitoring/docker/Dockerfile .
    args:
      chdir: ~/deploy/logatec-experiment

  - name: Cleanup old docker container (controller-test)
    ignore_errors: yes
    command: "{{ item }}"
    with_items:
      - docker kill controller_ble
      - docker rm controller_ble

  - name: Run docker image
    command: docker run --name controller_ble -d --privileged -p 5561:5561 -p 5562:5562 -p 5563:5563 -e DEVICE_NUM={{device_num}} -e RADIO_TYPE={{radio_type}} controller-ble


    # TODO: rename container into testbed_controller