# TODO
# Option: run the script with strategy: free, so all the nodes will run simultaneously but they will not wait for each other 

---
- hosts: 192.168.12.81, 192.168.12.82, 192.168.12.83, 192.168.12.84, 192.168.12.85, 192.168.12.86, 192.168.12.87, 192.168.12.88, 192.168.12.89, 192.168.12.91, 192.168.12.92, 192.168.12.94, 192.168.12.95, 192.168.12.96, 192.168.12.97, 192.168.12.98, 192.168.12.99, 192.168.12.100, 192.168.12.101
# Nodes 81, 84 and 85 will produce noise..
  strategy: free
  remote_user: videk

# Select which application to test, duration in minutes
  vars:
    application: 05_benchmark-acs
    duration: 10
    autostart: false

# Display experiment abstract in build.log 
# TODO: How to display abstract only once, not at every node?
#  tasks:
#  - name: Display abstract
#    debug:
#      msg: "Testing {{application}}, duration {{duration}} minutes"
#    when: inventory_hostname == 192.168.12.81

  tasks:
  - name: Create directory
    file:
      path: ~/deploy/logatec-experiment
      state: directory

# Recursive option will also download the sub-modules
# Update will pull the changes from Github
# Force will delete local changes
# Version you can change which branch to pull
  - name: Pull changes from github
    git:
      repo: git@github.com:logatec3/logatec-experiment.git
      dest: ~/deploy/logatec-experiment
      recursive: no
      update: yes
      force: yes
      depth: 1
      version: develop/grega

# It is better to download sub-modules separately, otherwise you get 95MB of data instead 28MB
# Recursive option will download all sub-modules (also the ones from Contiki) which we don't need
  - name: Update submodules
    command: git submodule update --init
    args:
      chdir: ~/deploy/logatec-experiment

# Delete potential local changes (since force option in git task doesn't work for submodules)
  - name: Delete local changes
    shell: "{{ item }} "
    with_items:
      #- cd ~/deploy/logatec-experiment && git clean -f -d
      - cd ~/deploy/logatec-experiment/contiki-ng && git clean -f -d
      - cd ~/deploy/logatec-experiment/vesna-drivers && git clean -f -d

# Build...with -f flag so we can copy 'logatec-experiment' directory into container
  - name: Build docker file
    command: docker build -t logatec-experiment -f deployment/docker/Dockerfile . 
    args:
      chdir: ~/deploy/logatec-experiment

  - name: Cleanup old docker containers (target)
    register: target
    ignore_errors: yes
    command: "{{ item }}"
    with_items:
      - docker kill target
      - docker rm target

  - name: Run docker image
    command: docker run --name target --privileged --net=host -e TARGET=experiment_with_controller -e APP_DIR="{{application}}" -e APP_DURATION_MIN="{{duration}}" logatec-experiment
