---
- hosts: 192.168.12.81, 192.168.12.83
  remote_user: videk

  vars:
    application: 00_demo
    duration: 3

  - name: Create directory
    file:
      path: ~/deploy/logatec-experiment
      state: directory

# Recursive option will also download the sub-modules
# Update will pull the changes from Github
# Force will delete local changes
# Version you can change which branch to pull
  - name: Pull changes from github
    git:
      repo: git@github.com:logatec3/logatec-experiment.git
      dest: ~/deploy/logatec-experiment
      recursive: no
      update: yes
      force: yes
      depth: 1
      version: BLE

# -f flag so we can later copy whole LOG-a-TEC directory into container
# with Dockerfile command COPY...else we get error "Forbidden path outside the build context"
  - name: Build docker file
    command: docker build -t lgtc-ble-experiment -f deployment/docker/Dockerfile .
    args:
      chdir: ~/deploy/logatec-experiment

  - name: Cleanup old docker containers (target_BLE)
    register: target
    ignore_errors: yes
    command: "{{ item }}"
    with_items:
      - docker kill target_BLE
      - docker rm target_BLE

    # Root node
  - name: Run docker image 
    command: docker run -d --name target_BLE --privileged --net=host -it -e TARGET=run_experiment -e APP_DIR="{{application}}" -e APP_DURATION_MIN="{{duration}}" lgtc-ble-experiment
