
---
#############################################################################################################
# RELEASE CONTROLLER
#############################################################################################################
# Ansible playbook script that deploys the ECMS controller entity.
# Container is in daemon mode -  so Ansible continues to release_targets.yml
#
# Before deploying an experiment, select:
#
#   *) Device number - an optional variable to indicate how many devices are included in the experiment                   
#
#############################################################################################################

- hosts: videk_server
  remote_user: videk

  vars:
    technology: ble
    device_num: 21

  tasks: 
    - name: Create directory
      file:
        path: ~/deploy
        state: directory

    - name: Deploy experiment repository
      synchronize:
        src: "{{ lookup('env','PWD') }}"
        dest: ~/deploy
        delete: yes
        recursive: yes

    - name: Build docker file
      command: docker build -t ecms-controller -f monitor/docker/Dockerfile .
      args:
        chdir: ~/deploy/logatec-experiment

    - name: Cleanup old docker container (controller-test)
      ignore_errors: yes
      command: "{{ item }}"
      with_items:
        - docker kill controller-{{ technology }}
        - docker rm controller-{{ technology }}

    - name: Run docker image
      command: docker run --name controller-{{ technology }} -d --privileged -p 5561:5561 -p 5562:5562 -p 5563:5563 -e DEVICE_NUM={{ device_num }} -e RADIO_TYPE={{ technology }} ecms-controller 
