---
- hosts: 192.168.12.81
  strategy: free
  remote_user: videk

  # Select which application to test, duration in minutes and additional options (none/monitor/root/node)
  vars:
    technology: master
    application: 00_template
    duration: 20
    option: none

  tasks:
    - name: Create directory
      file:
        path: ~/deploy/logatec-experiment
        state: directory

  # Recursive option will also download the sub-modules
  # Update will pull the changes from Github
  # Force will delete local changes
  # Version you can change which branch to pull
    - name: Pull changes from github
      git:
        repo: git@github.com:logatec3/logatec-experiment.git
        dest: ~/deploy/logatec-experiment
        recursive: no
        update: yes
        force: yes
        depth: 1
        version: "{{ technology }}"
  
  # It is better to download sub-modules separately, otherwise you get 95MB of data instead 28MB
  # Recursive option will download all sub-modules (also the ones from Contiki) which we don't need
    - name: Update submodules
      command: git submodule update --init
      args:
        chdir: ~/deploy/logatec-experiment
  
  # Delete potential local changes (since force option in git task doesn't work for submodules)
    - name: Delete local changes
      shell: "{{ item }} "
      with_items:
        #- cd ~/deploy/logatec-experiment && git clean -f -d
        #- cd ~/deploy/logatec-experiment/contiki-ng && git clean -f -d
        #- cd ~/deploy/logatec-experiment/vesna-drivers && git clean -f -d
  
    - name: Build the docker file
      command: docker build -t logatec-experiment -f deployment/docker/Dockerfile . 
      args:
        chdir: ~/deploy/logatec-experiment
  
    - name: Cleanup old docker containers
      ignore_errors: yes
      command: "{{ item }}"
      with_items:
        - docker kill target-{{ technology }}
        - docker rm target-{{ technology }}
  
    - name: Run docker container
      command: docker run --name target-{{technology}} --privileged --net=host -e APP="{{application}}" -e APP_DUR="{{duration}}" -e OPTION="{{option}}" logatec-experiment
  